name: Run Streamlit App
on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Deploy to Kubernetes
        run: |
          kubectl create deployment streamlit-app --image=${{ secrets.DOCKER_USERNAME }}/agile-ml-dl-qml
          kubectl expose deployment streamlit-app --type=NodePort --port=8501

      - name: Wait for Pod
        run: kubectl wait --for=condition=available --timeout=120s deployment/streamlit-app

      - name: Get Pods
        run: kubectl get pods

      - name: Get Service
        run: kubectl get svc

      - name: Describe Deployment
        run: kubectl describe deployment streamlit-app